version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=galkaev
    ports:
      - 8083:8080

  backend:
    image: anttiheimonen/backend
    build: ./backend
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db
      - REDIS=redis
      - FRONT_URL=http://localhost

  redis:
    image: redis

  frontend:
    image: anttiheimonen/frontend
    build: ./frontend
    environment:
      - API_URL=http://localhost/api

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database:

