version: '3.5'

services:
  builder:
    image: dockerindocker
    build: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - GIT_REPOSITORY
      - IMAGE_TAG