FROM alpine:3.7

WORKDIR /app
RUN apk add --no-cache curl openjdk8 && \
  export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk && \
  export PATH=$PATH:$JAVA_HOME/bin && \
  curl -L https://github.com/docker-hy/spring-example-project/tarball/master | tar xz --strip-components=1 && \
  apk del curl && \
  ./mvnw package && \
  rm mvnw && rm README.md && rm mvnw.cmd && rm pom.xml && rm -r .mvn && rm -r src && rm .gitignore && \
  adduser -D app

USER app
WORKDIR /app
ENTRYPOINT ["java", "-jar", "./target/docker-example-1.1.3.jar"]