version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=galkaev
    ports:
      - 8083:8080

  backend:
    image: anttiheimonen/backend
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db
      - REDIS=redis

  redis:
    image: redis

  frontend:
    image: anttiheimonen/frontend
    build: ./frontend
    ports:
      - 5000:5000

# volumes:
#   database:

