version: '3' 

services: 
    backend:  
      image: anttiheimonen/backend
      build: ./backend
      ports:
        - 8000:8000

    frontend:
      image: anttiheimonen/frontend
      build: ./frontend 
      ports:
        - 5000:5000
