version: '3' 

services: 
    backend:  
      image: anttiheimonen/backend
      build: ./backend
      ports:
        - 8000:8000
      environment:
        - REDIS=redis

    redis:
      image: redis


