version: '3.5'

services:
  backend:
    image: anttiheimonen/backend
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  frontend:
    image: anttiheimonen/frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000

  training:
    image: anttiheimonen/training
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - images:/src/imgs

volumes:
  model:
  images:

